language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq >/dev/null 2>&1
  - sudo apt-get install -qq libevent-dev >/dev/null 2>&1
  - git clone https://github.com/akheron/jansson.git
  - cd jansson
  - autoreconf -i
  - ./configure
  - make
  - sudo make install
  - cd -
  - pkg-config --modversion jansson
  - pkg-config --modversion libevent
script:
  - make CC=$CC
  - make CC=$CC -C contrib/weather_dot_json
notifications:
  irc:
    channels:
      - "irc.freenode.org#schoentoon"
    on_success: always
    on_failure: always
